name: coverage
on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1

      - name: Make fresh
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          make fresh

      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          flag-name: Unit Test

      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: svg.snoweb.fr
          username: debian
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            cd /home/debian/bin/ && ./snowebsvg_deploy.sh


  coveralls_finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel-finished: true